### ISSUE TITLE
SSL/TLS support

### ISSUE THREAD

**Issue by lz1irq** [coleifer/irc#15]
Disregard, the text below, I've submitted a pull request - #16 

In order to use the redis bot on the IRC server I frequent I had to patch the library so that it uses SSL/TLS. I think it would be useful to add this functionality to the library but I was wondering what approach to take - let the programmer specify whether they want to use SSL, auto-detect based on port (6697), or maybe both

**Comment by coleifer** [comment]
Merged #16, thanks!
